export enum RouterNames {
    HOME = "/",
    INSTITUTE = "/institute",
    ENTRANTS = "/entrants",
    STUDY = "/study",
    CONTACTS = "/contacts",
    NEWS = "/news",
    SCIENCE = "/science",
    FACULTY = "/faculty",
    DEPARTMENT = "/department",
    UNIT = "/unit",
    COOPERATION = "/cooperation",
    OUR_WINS = "/wins",
    SPECIALITIES = "/specialities",
    CHIEFS = "/institute/chiefs",
    WHY_MITIT = "/institute/why",
    HISTORY = "/institute/history",
    PUBLIC_INFO = "/institute/public",
    HEROES = "/institute/heroes"
}